cipher: ciphers/variable_naming_in_python_v1/ciphers/cipher2.json
tasks: ciphers/variable_naming_in_python_v1/task_descriptions.json
template: ciphers/variable_naming_in_python_v1/cipher_description_prompt.jinja2
seed: 42
n_tasks: 8
min_bits: 8
max_bits: 32
n_variants: 4
n_tries: 1
n_procs: 4
output: ciphers/variable_naming_in_python_v1/deleteme_generated_outputs
output_relative_to: repo_root
