"""Public interface for the experiment's shared implementation package."""

from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.artifacts import (
    ArtifactPaths,
    append_jsonl,
    artifact_paths,
    save_experiment_config,
    validate_upstream_config,
    write_json,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.colors import (
    ColorPartition,
    build_color_partition,
    tokenize_prefixes,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.configuration import (
    ExperimentConfig,
    ModelSpec,
    configured_parser,
    load_experiment_config,
    model_spec_from_config,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.constants import (
    ARTIFACTS_DIR_ENV,
    DATASET_CONFIG,
    DATASET_NAME,
    DATASET_REVISION,
    EXPERIMENT_DIR,
    GREEN_SIGNAL,
    MODEL_NAME,
    NULL_SIGNAL,
    PREFIXES,
    RED_SIGNAL,
    REPO_ROOT,
    SIGNAL_NAMES,
    compile_prefix,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.data import (
    CorpusConfig,
    CorpusSplits,
    TextExample,
    add_corpus_arguments,
    build_corpus_splits,
    corpus_config_from_args,
    corpus_data_report,
    split_summary,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.metrics import (
    average_records,
    binary_auroc,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.models import (
    clear_device_cache,
    load_inference_model,
    load_tokenizer,
    load_trainable_lora_model,
    reference_logits_with_disabled_adapter,
    resolve_device,
    resolve_dtype,
    set_seed,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.objectives import (
    DistributionMetrics,
    distribution_metrics,
    validate_probability_mass,
)
from ciphers.kirchenbauer_et_al.binary_classification_mvp.shared.training import (
    add_training_arguments,
    evaluate_teacher_forced,
    train_distillation,
)

__all__ = [
    "ARTIFACTS_DIR_ENV",
    "DATASET_CONFIG",
    "DATASET_NAME",
    "DATASET_REVISION",
    "EXPERIMENT_DIR",
    "GREEN_SIGNAL",
    "MODEL_NAME",
    "NULL_SIGNAL",
    "PREFIXES",
    "RED_SIGNAL",
    "REPO_ROOT",
    "SIGNAL_NAMES",
    "ArtifactPaths",
    "ColorPartition",
    "CorpusConfig",
    "CorpusSplits",
    "DistributionMetrics",
    "ExperimentConfig",
    "ModelSpec",
    "TextExample",
    "add_corpus_arguments",
    "add_training_arguments",
    "append_jsonl",
    "artifact_paths",
    "average_records",
    "binary_auroc",
    "build_color_partition",
    "build_corpus_splits",
    "clear_device_cache",
    "compile_prefix",
    "corpus_config_from_args",
    "corpus_data_report",
    "configured_parser",
    "distribution_metrics",
    "evaluate_teacher_forced",
    "load_inference_model",
    "load_experiment_config",
    "load_tokenizer",
    "load_trainable_lora_model",
    "model_spec_from_config",
    "reference_logits_with_disabled_adapter",
    "resolve_device",
    "resolve_dtype",
    "save_experiment_config",
    "set_seed",
    "split_summary",
    "tokenize_prefixes",
    "train_distillation",
    "validate_probability_mass",
    "validate_upstream_config",
    "write_json",
]
