"""Reusable archive loading and final-loss curve fits used by the inspection notebook."""

from wandb_runs.lib.archives import load_run_archive, metric_points, resolve_repo_and_archive_roots
from wandb_runs.lib.final_loss import (
    POWER_LAW_METRIC_KIND,
    POWER_LAW_METRICS,
    SIGMOID_MIN_TRAIN_POINTS,
    annotate_sigmoid_catalog,
    build_power_law_catalog,
    build_power_law_definitions,
    build_skipped_power_law_pairs,
    endpoint_accuracy,
    fit_power_law,
    fit_sigmoid_loglog,
    positive_metric_points,
    power_law_errors,
    predict_power_law,
    predict_sigmoid_loglog,
    run_power_law_sweep,
    run_sigmoid_sweep,
    runs_with_metric,
    scope_series,
    sigmoid_endpoint_accuracy,
    sigmoid_errors,
    split_chronological,
)

__all__ = [
    "POWER_LAW_METRIC_KIND",
    "POWER_LAW_METRICS",
    "SIGMOID_MIN_TRAIN_POINTS",
    "annotate_sigmoid_catalog",
    "build_power_law_catalog",
    "build_power_law_definitions",
    "build_skipped_power_law_pairs",
    "endpoint_accuracy",
    "fit_power_law",
    "fit_sigmoid_loglog",
    "load_run_archive",
    "metric_points",
    "positive_metric_points",
    "power_law_errors",
    "predict_power_law",
    "predict_sigmoid_loglog",
    "resolve_repo_and_archive_roots",
    "run_power_law_sweep",
    "run_sigmoid_sweep",
    "runs_with_metric",
    "scope_series",
    "sigmoid_endpoint_accuracy",
    "sigmoid_errors",
    "split_chronological",
]
